### PR TITLE
feat: remove skipped tests

### PR DESCRIPTION
**Pull request by theodu**

### CODE REVIEW

**Review by PierreLeveau — APPROVED** [review]

**Comment by theodu** [comment]
@Jonas1312 E2E test did not raise the expected error with invalid json: https://github.com/kili-technology/kili-python-sdk/actions/runs/5936602105/job/16097372790.
When I test the feature in local, It actually raises an error. I should expect another error than a graphQLError from kili.exceptions?

**Comment by Jonas1312** [comment]
works well for me locally, I rerun the tests

are you sure you have enabled the feature for test+admin+1 account?

**Comment by Jonas1312** [comment]
it failed again, so it's related to the test account

**Comment by theodu** [comment]
yeah but the feature is activated for all users on staging..

**Pull request merged**
